// Generated by CoffeeScript 1.9.3
d3.select("span#fade").on("click", function() {
  console.log("click");
  return d3.select(this).transition().duration(5000).ease("linear").style("opacity", 0).transition().delay(6500).duration(0).remove();
});
